### ISSUE TITLE
Github Pages for this Project?

### ISSUE THREAD

**Issue by pbnj** [riebschlager/linkedin-recruiter-email#6]
I tried hitting https://riebschlager.github.io/linkedin-recruiter-email to see the index.html rendered in the browser, but no luck. 

Am I missing something here?

**Comment by riebschlager** [comment]
You are certainly not missing anything here. This was a project I finished over my morning coffee for a few laughs. But you are absolutely right, a github pages for this project makes total sense. I'm on it.

**Comment by riebschlager** [comment]
Done and done. Thanks for the suggestion.

https://riebschlager.github.io/linkedin-recruiter-email/
